### PR TITLE
Changing packaging structure

### PR DESCRIPTION
**Pull request by aradhakrishnanGFDL**
We need a sub-package structure, as in one can import just catalogs, or the wrapper scripts, or the API itself, or get all at once. But, also noting that going forward the catalogs perhaps will also be pushed to a schema repo. 

Given the landscape change, we are revisiting the way packaging was done and see if technical issues can be resolved to get this done, collectively.

### CODE REVIEW

**Comment by aradhakrishnanGFDL** [comment]
@ilaflott with the changes in the PR, we should be able to the following

from catalogbuilder.scripts import gen_intake_gfdl

and hopefully be able to do the following

conda install noaa-gfdl::catalogbuilder

and bonus
conda install catalogbuilder.scripts -c noaa-gfdl 

Someone needs to remove the intakebuilder package once this PR is approved, and communicate to ensure analysis-scripts is updated. 

@ilaflott Do you know how to update the CONDA tokens (if GitHub teams allow)? See a silent failure [here](https://github.com/NOAA-GFDL/CatalogBuilder/actions/runs/10013559062/job/27681452273?pr=5#step:4:598)

**Comment by aradhakrishnanGFDL** [comment]
I've opened a couple issues for those that could be addressed in a different PR so this is a bit manageable to review. Appreciate quick improvements and fixes needed to address this PR.. while the bigger ones can be new "issues" to address later.

**Comment by ilaflott** [comment]
> @ilaflott with the changes in the PR, we should be able to the following
> 
> from catalogbuilder.scripts import gen_intake_gfdl
> 
I can confirm this in a clean environment but i am getting a warning with a fresh code checkout:
```
Python 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import catalogbuilder
>>> from catalogbuilder.scripts import gen_intake_gfdl
The module intakebuilder is not installed. Do you have intakebuilder in your sys.path or have you activated the conda environment with the intakebuilder package in it?
Attempting again with adjusted sys.path
```

which brings [me to these lines that i find confusing](https://github.com/NOAA-GFDL/CatalogBuilder/blob/subpkgtest/catalogbuilder/scripts/gen_intake_gfdl.py#L13-L26). it does seem to work though.

> and hopefully be able to do the following
> 
> conda install noaa-gfdl::catalogbuilder
> and bonus conda install catalogbuilder.scripts -c noaa-gfdl
> 
happy to test that out upon publishing pipeline, which runs on merge i take it?

> Someone needs to remove the intakebuilder package once this PR is approved, and communicate to ensure analysis-scripts is updated.
> 
> @ilaflott Do you know how to update the CONDA tokens (if GitHub teams allow)? See a silent failure [here](https://github.com/NOAA-GFDL/CatalogBuilder/actions/runs/10013559062/job/27681452273?pr=5#step:4:598)

sorry i haven't touched github secrets and/or conda tokens. I am unsure if i even have permissions, we can chat elsewhere about this if we need.

**Comment by ilaflott** [comment]
I pushed a super small tweak to the reqs detailed in the `meta.yaml` and `setup.py`

**Comment by ilaflott** [comment]
@Ciheim i think you can set the secrets for the respository? https://github.com/orgs/NOAA-GFDL/teams/catalogbuilder-admins

**Comment by aradhakrishnanGFDL** [comment]
> > @ilaflott with the changes in the PR, we should be able to the following
> > from catalogbuilder.scripts import gen_intake_gfdl
> 
> I can confirm this in a clean environment but i am getting a warning with a fresh code checkout:
> 
> ```
> Python 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import catalogbuilder
> >>> from catalogbuilder.scripts import gen_intake_gfdl
> The module intakebuilder is not installed. Do you have intakebuilder in your sys.path or have you activated the conda environment with the intakebuilder package in it?
> Attempting again with adjusted sys.path
> ```
> 
> which brings [me to these lines that i find confusing](https://github.com/NOAA-GFDL/CatalogBuilder/blob/subpkgtest/catalogbuilder/scripts/gen_intake_gfdl.py#L13-L26). it does seem to work though.

Right, if the conda package is installed and user activates the environment, you won't see this error. Since users have an option to run the catalog builder without the conda package, we expect them to add the necessary system paths so we can find the intakebuilder. We do need a new CI test that tests the conda package upon publishing (also a GitHub issue, though unsure when it will be taken up)

> 
> > and hopefully be able to do the following
> > conda install noaa-gfdl::catalogbuilder
> > and bonus conda install catalogbuilder.scripts -c noaa-gfdl
> 
> happy to test that out upon publishing pipeline, which runs on merge i take it?
> 
> > Someone needs to remove the intakebuilder package once this PR is approved, and communicate to ensure analysis-scripts is updated.
> > @ilaflott Do you know how to update the CONDA tokens (if GitHub teams allow)? See a silent failure [here](https://github.com/NOAA-GFDL/CatalogBuilder/actions/runs/10013559062/job/27681452273?pr=5#step:4:598)
> 
> sorry i haven't touched github secrets and/or conda tokens. I am unsure if i even have permissions, we can chat elsewhere about this if we need.

I've added the secret. The [conda publish CI pipeline](https://github.com/NOAA-GFDL/CatalogBuilder/actions/runs/10045906528/job/27765083978) is now working as expected per the logs. Though it's not approved - I did push the package to the noaa-gfdl channel through this CI (have issues opened, we need a test channel or something too later). So conda install could be tested now.

**Comment by aradhakrishnanGFDL** [comment]
@ilaflott https://anaconda.org/noaa-gfdl/catalogbuilder is now up!

**Comment by ilaflott** [comment]
so `conda install noaa-gfdl::catalogbuilder` works, but...
```
(ians_CLEAN_env) ldt-4788479: ~ $] python
Python 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import catalogbuilder
>>> from catalogbuilder.scripts import gen_intake_gfdl
The module intakebuilder is not installed. Do you have intakebuilder in your sys.path or have you activated the conda environment with the intakebuilder package in it?
Attempting again with adjusted sys.path
```

now i look back at those import lines we WANT to work, in the `try` blocks:
```
from intakebuilder import gfdlcrawler, CSVwriter, builderconfig, configparser
```
this won't work because the package is no longer called `intakebuilder`, it's called `catalogbuilder`, and these pieces are under `catalogbuilder.intakebuilder` [here](https://github.com/NOAA-GFDL/CatalogBuilder/tree/subpkgtest/catalogbuilder/intakebuilder). that's why python can't find those scripts and why the `dirname(dirname(filename)))` output getting added to `sys.path` works to solve the import issue- it's essentially saying "look for the scripts at the root directory of this package"

If we adjust the import calls, we can avoid `sys.path` manipulation, change the line to instead:
```
from catalogbuilder.intakebuilder import gfdlcrawler, CSVwriter, builderconfig, configparser
```

...or i can even use a relative import:
```
from . import gfdlcrawler, CSVwriter, builderconfig, configparser
```

... and changing the same import lines in applicable files within `catalogbuilder/intakebuilder` and we get the desired behavior, no warning.

**Comment by ilaflott** [comment]
not sure `conda install catalogbuilder.scripts -c noaa-gfdl` its working as excpected. but that being said, the package is quite small anyways, so i dont think the incentive to get this installation mode working is huge. The main approach, `conda install noaa-gfdl::catalogbuilder` works well and is more important.
```
(ians_CLEAN_env) ldt-4788479: ~ $] mamba install catalogbuilder.scripts -c noaa-gfdl

Looking for: ['catalogbuilder.scripts']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
r/linux-64                                                  Using cache
r/noarch                                                    Using cache
noaa-gfdl/linux-64                                            No change
noaa-gfdl/noarch                                              No change
main/linux-64                                                 No change
main/noarch                                                   No change
Could not solve for environment specs
The following package could not be installed
└─ catalogbuilder.scripts does not exist (perhaps a typo or a missing channel).
(ians_CLEAN_env) ldt-4788479: ~ $] conda install catalogbuilder.scripts -c noaa-gfdl
Channels:
 - noaa-gfdl
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - catalogbuilder.scripts

Current channels:

  - https://conda.anaconda.org/noaa-gfdl
  - defaults
  - https://conda.anaconda.org/conda-forge

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by ilaflott** [comment]
Well i certainly see the challenge in keeping both a user's interactive python shell happy, and github's CI/CD pipeline happy, at the same time.

... python packaging, sigh...

**Review by ilaflott — APPROVED** [review]
i reverted back to the state it was in when i introduced a tiny tweak. pipeline passes. will look at this in other issues/branches/PRs as you suggested- nontrivial for some reason.

honestly, i think we're fighting the pipeline+it's env much more than we are the packaging. those two sets of problems LOOK very similar, though.

**Review by ceblanton — APPROVED** [review]
Yes! thanks for this, @ilaflott

**Pull request merged**
