### PR TITLE
Rename scripts to CatalogBuilder

### LINKED ISSUE #3: Rename scripts to catalogbuilder
For readability, usability and fre-cli coherency.

### PR DESCRIPTION
**Pull request by ceblanton**
resolves #3 

After pip installing, `gen_intake_gfdl` is available from `CatalogBuilder` as expected.

```
>python 
Python 3.6.8 (default, Apr 25 2024, 09:54:46) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import intakebuilder
>>> import CatalogBuilder
>>> from CatalogBuilder import gen_intake_gfdl
```

This will let fre-cli import this functionality in a clearly catalog-related namespace.

### CODE REVIEW

**Comment by aradhakrishnanGFDL** [comment]
sticking with lowercase package names is consistent with https://docs.conda.io/projects/conda-build/en/latest/concepts/package-naming-conv.html and is more usable.

**Comment by ilaflott** [comment]
> resolves #3
> 
> After pip installing, `gen_intake_gfdl` is available from `CatalogBuilder` as expected.
> 
> ```
> >python 
> Python 3.6.8 (default, Apr 25 2024, 09:54:46) 
> [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import intakebuilder
> >>> import CatalogBuilder
> >>> from CatalogBuilder import gen_intake_gfdl
> ```
> 
> This will let fre-cli import this functionality in a clearly catalog-related namespace.

I don't think this is really what we want. This makes `conda install noaa-gfdl::intakebuilder` puts `cats`, `intakebuilder`, and `CatalogBuilder` all in the base namespace. that is pretty confusing.

I think we would rather the structure be-
```
intakebuilder/
    cats/
    catalogbuilder/ #formerly scripts/
    tests/
```

So your imports become:
```
import intakebuilder
from intakebuilder import catalogbuilder
from catalogbuilder import gen_intake_gfdl
```

this way all the directories also end up under `intakebuilder` in your `conda/env/.../site-packages` directory.

**Comment by aradhakrishnanGFDL** [comment]
> > resolves #3
> > After pip installing, `gen_intake_gfdl` is available from `CatalogBuilder` as expected.
> > ```
> > >python 
> > Python 3.6.8 (default, Apr 25 2024, 09:54:46) 
> > [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] on linux
> > Type "help", "copyright", "credits" or "license" for more information.
> > >>> import intakebuilder
> > >>> import CatalogBuilder
> > >>> from CatalogBuilder import gen_intake_gfdl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will let fre-cli import this functionality in a clearly catalog-related namespace.
> 
> I don't think this is really what we want. This makes `conda install noaa-gfdl::intakebuilder` puts `cats`, `intakebuilder`, and `CatalogBuilder` all in the base namespace. that is pretty confusing.
> 
> I think we would rather the structure be-
> 
> ```
> intakebuilder/
>     cats/
>     catalogbuilder/ #formerly scripts/
>     tests/
> ```
> 
> So your imports become:
> 
> ```
> import intakebuilder
> from intakebuilder import catalogbuilder
> from catalogbuilder import gen_intake_gfdl
> ```
> 
> this way all the directories also end up under `intakebuilder` in your `conda/env/.../site-packages` directory.

Good points. There is some history behind this, and its good to revisit the structure and knock off any packaging issues that we once faced with. I am opening a new PR to see if we can get some consensus. Will need conda packaging expertise should the  CI tests fail due to the meta.yml setup. see you on a new PR.

**Comment by aradhakrishnanGFDL** [comment]
closing this.. see https://github.com/NOAA-GFDL/CatalogBuilder/pull/5

**Pull request closed without merging**
