### PR TITLE
print to logger debug

### PR DESCRIPTION
**Pull request by aradhakrishnanGFDL**
associated with #69

### CODE REVIEW

**Comment by aradhakrishnanGFDL** [comment]
Issue has a notebook with an example in case the user wants to redirect debug messages to a separate log file. I expect fre-cli will do this internally for those that use fre-cli, but that might be tricky @ceblanton?

**Comment by aradhakrishnanGFDL** [comment]
im going to add the silent and verbose options. what should the default be? @ceblanton @jkrasting

**Comment by aradhakrishnanGFDL** [comment]
--verbose added, by default its silent. 

`csv, json = gen_intake_gfdl.create_catalog(input_path=input_path,output_path=output_path,config=configyaml)
`
If you want verbose you'd pass verbose=True 
`
csv, json = gen_intake_gfdl.create_catalog(input_path=input_path,output_path=output_path,config=configyaml,verbose=True)
`
Interactive test with gen_intake_gfdl.py --verbose option untested

**Comment by aradhakrishnanGFDL** [comment]
@ceblanton this is back for a review. Please see my notes in terms of what was tested and what was not. I will need help testing the interactive option, and I can get to fixing broken things based on the notes passed along via this PR

**Review by ceblanton — APPROVED** [review]
Looks good. Totally agree with using the logger module instead of printing.

**Comment by ceblanton** [comment]
Hand tests show the expected behavior. --verbose is a bit overly verbose and we might have to tune it down, but more details are better than fewer

**Pull request merged**
