### PR TITLE
Mdtf support- Add schema file to config yaml

### PR DESCRIPTION
**Pull request by aradhakrishnanGFDL**
This adds a new feature to pass a "schema" to the config file so the gfdl-template.json is undisturbed as other related applications are being tested. 

So, to test do this

./gen_intake_gfdl.py --config ../tests/config-mdtf.yaml

where config-mdtf.yaml is in this repos catalogbuilder/tests directory
The config has a "schema" set which points to 

schema: "/home/a1r/git/forkCatalogBuilder-/catalogbuilder/cats/mdtf_template.json"
(see in /catalogbuilder/cats/mdtf_template.json in this repository)

So, the resulting json will have a time_range in aggregate columns as the above schema suggests. This feature ensures that gfdl_template.json does not use this setting by default, and the example template here for mdtf will likely evolve once best practices are established to identify unique, aggregated datasets.

### CODE REVIEW

**Comment by aradhakrishnanGFDL** [comment]
addresses #28

**Comment by aradhakrishnanGFDL** [comment]
@Ciheim please review and test as needed so this can be merged before Wednesday. Suggest changes inline as needed. thanks!

**Review by ceblanton — APPROVED** [review]
I don't like the `enhanced` option for required or not (I realize it was my idea).

Shouldn't it be merely required yes or no? standard_name required for mdtf, not for regular GFDL use.

**Comment by ceblanton** [comment]
Let's remove "enhanced" as a valid `required` option.

https://github.com/NOAA-GFDL/CatalogBuilder/issues/34

**Pull request merged**
