### PR TITLE
Combine cats

### PR DESCRIPTION
**Pull request by aradhakrishnanGFDL**
Initial attempt to address #56.
Encourage user contributions to make the tool robust and more usable. 

Here's the current user interface

```
combine_cats.py --help
Usage: combine_cats.py [OPTIONS]

  This script combines two json catalogs. It takes the path to input catalogs
  and the output catalog names as input. The options may be passed with this
  as the template:  combine_catalogs.py -i jsoncatalog -i jsoncatalog2 -o
  outputjson

  Example usage: combine_cats.py -i /home/a1r/github/noaa-
  gfdl/catalogs/CM4.5v01_om5b06_piC_noBLING.json -i /home/a1r/github/noaa-
  gfdl/catalogs/ESM4.5v01_om5b04_piC.json -o combinedcat.json

Options:
  -i, --inputfiles TEXT   Pass json catalog files to-be-combined, space
                          separated  [required]
  -o, --output_path TEXT  Specify the output json path  [required]
  --help                  Show this message and exit.

```

You may test it with this:

```
combine_cats.py -i /home/a1r/github/noaa-
  gfdl/catalogs/CM4.5v01_om5b06_piC_noBLING.json -i /home/a1r/github/noaa-
  gfdl/catalogs/ESM4.5v01_om5b04_piC.json -o combinedcat.json
```

I have an example of a combined catalog here: 
/home/a1r/github/noaa-gfdl/catalogs/CM4_and_ESM45_combined.json

The script ensures the diff of the two json catalogs passed is nearly zero (except for catalog_file path) and then uses pandas to concatenate. The header files are used from one of the input files.

### CODE REVIEW

**Comment by aradhakrishnanGFDL** [comment]
@ceblanton Feel free to use this script with fre-cli with more bells and whistles.

**Comment by ceblanton** [comment]
Thanks! I'm sure this is at least in exactly the right direction so I think we should take it and improve it as we go, even if it's not perfect yet.

**Review by ceblanton — CHANGES_REQUESTED** [review]
Thanks! It works as expected, except this line:

df_concat = df_concat.drop(['Unnamed: 0'],axis=1)

causes an error. Removing that gets past it. Can we omit it?

KeyError: "['Unnamed: 0'] not found in axis"

**Comment by aradhakrishnanGFDL** [comment]
> Thanks! It works as expected, except this line:
> 
> df_concat = df_concat.drop(['Unnamed: 0'],axis=1)
> 
> causes an error. Removing that gets past it. Can we omit it?
> 
> KeyError: "['Unnamed: 0'] not found in axis"

Yes nice catch! This is because of the big fix made to remove the first unnamed index in a recent PR.

**Comment by aradhakrishnanGFDL** [comment]
> > Thanks! It works as expected, except this line:
> > df_concat = df_concat.drop(['Unnamed: 0'],axis=1)
> > causes an error. Removing that gets past it. Can we omit it?
> > KeyError: "['Unnamed: 0'] not found in axis"
> 
> Yes nice catch! This is because of the big fix made to remove the first unnamed index in a recent PR.

this if now fixed. Feel free to merge it in!

**Review by ceblanton — APPROVED** [review]
This could still use improvements no doubt, but we're merging this so lets continue to improve it as we use it more.

**Pull request merged**
